"""Review and the Repair Router (Phases 7 and 8).

Deterministic technical validators run first; expensive AI review is never the
only validation layer. Review returns only structured ``ReviewIssue`` records —
free-form text is not an acceptable review output, because automation depends on
structure.

The Repair Router sends each issue back to the node responsible for fixing it
via a table-driven policy, and repairs the smallest responsible scope.

Step 1.6 shipped a thin open-issue binding store so re-segmentation can
re-target or close open issues when scene ids change. Step 7.1 adds
deterministic technical validators. Step 7.2 expands open-issue bindings into
the full ReviewIssue schema and durable store. Step 7.4 adds early quality
gates (image before video, video before final review). Step 8.1 freezes the
§12.2 ownership table as ``scriptase.review.policy``. Step 8.2 adds targeted
repair with per-issue attempt budgets, Job generation/cost ceilings, escalation,
and safe degradation (``scriptase.review.repair``). Step 8.4 persists every
repair outcome as a ``RepairHistoryEntry`` tied to superseded artifact versions
(``scriptase.review.history``). Step 11.2 connects the two halves: the Review
node's findings are persisted and linked to their Job by
``scriptase.review.emission``, so a real run finally produces ReviewIssues for
the Repair Router to act on.
"""

from scriptase.review.emission import (
    attach_issues_to_job,
    emit_review_issues,
    issue_identity,
)
from scriptase.review.gates import (
    QUALITY_GATE_FAILED,
    GateUnit,
    QualityGateResult,
    enforce_image_gate_for_video,
    run_image_gate,
    run_video_gate,
    units_from_storyboard,
    units_from_video_assets,
)
from scriptase.review.models import (
    ISSUE_ID_RE,
    ISSUE_SCHEMA_VERSION,
    ISSUE_STATUSES,
    ISSUE_TYPES,
    OPEN_STATUSES,
    SEVERITIES,
    SUGGESTED_ACTIONS,
    TERMINAL_ISSUE_STATUSES,
    IssueStatus,
    IssueType,
    ReviewIssue,
    ReviewIssueDraft,
    Severity,
    SuggestedAction,
    assert_structured_review_result,
    parse_draft,
    parse_issue,
    technical_to_draft,
    validation_problems,
)
from scriptase.review.open_issues import (
    IssueBindingNotFound,
    OpenIssueBinding,
    assert_no_open_issue_on_dead_scenes,
    close_issues_for_scene,
    create_open_issue,
    retarget_issues,
)
from scriptase.review.policy import (
    CHECK_ID_PROBLEM,
    ISSUE_TYPE_DEFAULT_PROBLEM,
    OWNERSHIP_TABLE,
    PROBLEM_KEYS,
    RoutingDecision,
    UnknownRoutingProblem,
    UnroutableIssue,
    ownership_rows,
    resolve_problem_key,
    route_issue,
    route_problem,
)
from scriptase.review.history import (
    REPAIR_HISTORY_ACTIONS,
    REPAIR_HISTORY_ID_RE,
    REPAIR_HISTORY_RESULTS,
    REPAIR_HISTORY_SCHEMA_VERSION,
    RepairHistoryEntry,
    RepairHistoryError,
    RepairHistoryNotFound,
    RepairHistoryValidationError,
    create_repair_history_entry,
    get_repair_history_entry,
    list_repair_history,
    reconstruct_job_repair_history,
    record_repair_outcome,
)
from scriptase.review.repair import (
    BUDGET_EXCEEDED,
    DEFAULT_CONFIDENCE_FLOOR,
    LOW_CONFIDENCE,
    REPAIR_LIMIT_REACHED,
    SAFE_DEGRADATION,
    STATUS_REASON_BUDGET,
    STATUS_REASON_ESCALATION,
    STATUS_REASON_REPAIR_LIMIT,
    RepairBudgetError,
    RepairDecision,
    RepairLimitError,
    RepairPlan,
    RepairPolicy,
    apply_repair_decision,
    apply_repair_plan,
    build_repair_run_request,
    decide_issue_repair,
    plan_job_repairs,
    process_job_repairs,
    record_repair_attempt,
    resolve_repair_policy,
)
from scriptase.review.store import (
    IssueNotFound,
    IssueValidationError,
    create_from_review_result,
    create_from_technical,
    create_review_issue,
    get_issue,
    issues_for_nodes,
    list_issues,
    update_issue,
)
from scriptase.review.technical import (
    TECHNICAL_CHECK_IDS,
    MediaProbe,
    TechnicalContext,
    TechnicalIssue,
    assert_structured_issues,
    check_aspect_ratio,
    check_audio_presence,
    check_duration,
    check_expected_artifact_count,
    check_file_exists,
    check_frame_count,
    check_readable_media,
    check_resolution,
    probe_media,
    run_technical_validators,
)
from scriptase.review.viral_gate import (
    VIRAL_CHECK_ID,
    draft_for_score,
    gate_script_score,
    threshold_for_job,
    threshold_from_snapshot,
    viral_threshold,
)

__all__ = [
    "BUDGET_EXCEEDED",
    "CHECK_ID_PROBLEM",
    "DEFAULT_CONFIDENCE_FLOOR",
    "ISSUE_ID_RE",
    "ISSUE_SCHEMA_VERSION",
    "ISSUE_STATUSES",
    "ISSUE_TYPE_DEFAULT_PROBLEM",
    "ISSUE_TYPES",
    "LOW_CONFIDENCE",
    "OPEN_STATUSES",
    "OWNERSHIP_TABLE",
    "PROBLEM_KEYS",
    "QUALITY_GATE_FAILED",
    "REPAIR_HISTORY_ACTIONS",
    "REPAIR_HISTORY_ID_RE",
    "REPAIR_HISTORY_RESULTS",
    "REPAIR_HISTORY_SCHEMA_VERSION",
    "REPAIR_LIMIT_REACHED",
    "SAFE_DEGRADATION",
    "SEVERITIES",
    "STATUS_REASON_BUDGET",
    "STATUS_REASON_ESCALATION",
    "STATUS_REASON_REPAIR_LIMIT",
    "SUGGESTED_ACTIONS",
    "TECHNICAL_CHECK_IDS",
    "TERMINAL_ISSUE_STATUSES",
    "GateUnit",
    "IssueBindingNotFound",
    "IssueNotFound",
    "IssueStatus",
    "IssueType",
    "IssueValidationError",
    "MediaProbe",
    "OpenIssueBinding",
    "QualityGateResult",
    "RepairBudgetError",
    "RepairDecision",
    "RepairHistoryEntry",
    "RepairHistoryError",
    "RepairHistoryNotFound",
    "RepairHistoryValidationError",
    "RepairLimitError",
    "RepairPlan",
    "RepairPolicy",
    "ReviewIssue",
    "ReviewIssueDraft",
    "RoutingDecision",
    "Severity",
    "SuggestedAction",
    "TechnicalContext",
    "TechnicalIssue",
    "UnknownRoutingProblem",
    "UnroutableIssue",
    "apply_repair_decision",
    "apply_repair_plan",
    "assert_no_open_issue_on_dead_scenes",
    "assert_structured_issues",
    "assert_structured_review_result",
    "attach_issues_to_job",
    "build_repair_run_request",
    "check_aspect_ratio",
    "check_audio_presence",
    "check_duration",
    "check_expected_artifact_count",
    "check_file_exists",
    "check_frame_count",
    "check_readable_media",
    "check_resolution",
    "close_issues_for_scene",
    "create_from_review_result",
    "create_from_technical",
    "create_open_issue",
    "create_repair_history_entry",
    "create_review_issue",
    "decide_issue_repair",
    "emit_review_issues",
    "enforce_image_gate_for_video",
    "get_issue",
    "get_repair_history_entry",
    "issue_identity",
    "issues_for_nodes",
    "list_issues",
    "list_repair_history",
    "ownership_rows",
    "parse_draft",
    "parse_issue",
    "plan_job_repairs",
    "probe_media",
    "process_job_repairs",
    "reconstruct_job_repair_history",
    "record_repair_attempt",
    "record_repair_outcome",
    "resolve_problem_key",
    "resolve_repair_policy",
    "retarget_issues",
    "route_issue",
    "route_problem",
    "run_image_gate",
    "run_technical_validators",
    "run_video_gate",
    "technical_to_draft",
    "units_from_storyboard",
    "units_from_video_assets",
    "update_issue",
    "validation_problems",
    "VIRAL_CHECK_ID",
    "draft_for_score",
    "gate_script_score",
    "threshold_for_job",
    "threshold_from_snapshot",
    "viral_threshold",
]
