"""Scaffold check provider manifest — Provider Contract v2.

Generated by `python -m scriptase.providers.scaffold`.
"""

from scriptase.providers import ProviderManifest


def manifest() -> ProviderManifest:
    return ProviderManifest(
        id="scaffold_check",
        label="Scaffold check",
        domain="script",
        kind="local",
        version="1.0.0",
        contract_version=2,
        requires=[],
        capabilities={
            'test_connection': True,
            'offline': True,
            'single_scene': True,
            'structured_sections': False,
            'language_select': True,
            'batch': False,
        },
        description=(
            "Scaffolded Scaffold check provider for the script domain. Replace the implementation body; keep the package layout."
        ),
        environment={},
    )
