"""Scaffold check script provider — Provider Contract v2.

Generated by `python -m scriptase.providers.scaffold`.
A deterministic offline document producer so the package is discovered,
API-visible, UI-configurable, and executable on `story.generate` without edits.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import Any, Mapping

from config import STORIES_DIR
from scriptase.shared.io_utils import safe_json_write
from scriptase.modules.script.providers.base import ScriptProvider
from scriptase.modules.script.providers.contract import ScriptRequest, ScriptResultPayload


class ScaffoldCheckProvider(ScriptProvider):
    """Offline scaffold demo: turns idea + optional prefix into a short script."""

    def generate(self, configuration: Mapping[str, Any], *, project_id: str) -> dict:
        request = ScriptRequest.from_configuration(configuration)
        settings = dict(configuration or {})
        prefix = str(settings.get("label_prefix") or "Scaffold check").strip() or "Scaffold check"
        idea = (request.idea or "an offline scaffold demo").strip()
        script_text = f"{prefix}: {idea}"
        word_count = len(script_text.split())
        estimated = max(1, round(word_count / 2.5))
        language = request.language or str(settings.get("language") or "english")
        payload = ScriptResultPayload(
            script_text=script_text,
            sections={"hook": script_text, "cta": f"{prefix} complete"},
            word_count=word_count,
            estimated_duration_s=estimated,
            language=language,
        )
        generated_at = datetime.now(timezone.utc).isoformat()
        story_data = {
            "project_id": project_id,
            "story_text": payload.script_text,
            "sections": dict(payload.sections),
            "metadata": {
                "preset_style": request.style or "",
                "language": payload.language,
                "story_category": request.category or "",
                "story_tone": request.tone or "",
                "duration": request.target_duration_s,
                "word_count": payload.word_count,
                "estimated_duration": payload.estimated_duration_s,
                "provider": "scaffold_check",
                "timestamp": generated_at,
            },
            "pipeline_ref": {"tts_project_id": None, "scenes_project_id": None},
        }
        path = os.path.join(STORIES_DIR, project_id, "story.json")
        safe_json_write(path, story_data, indent=2)
        return {**story_data, "path": path}


def create() -> ScaffoldCheckProvider:
    return ScaffoldCheckProvider()


def validate_settings(settings: dict) -> list[dict]:
    issues: list[dict] = []
    language = str((settings or {}).get("language") or "english").strip().lower()
    if language and language not in ("english", "french", "spanish"):
        issues.append({
            "field": "language",
            "severity": "warning",
            "message": f"Unsupported language '{language}'",
        })
    return issues


def health_check(settings: dict) -> dict:
    return {
        "status": "ok",
        "latency_ms": 0,
        "message": "Offline scaffold provider ready",
    }
