"""Job: one video-production run, plus the stage projection of its workflow.

Populated in steps 1.4, 1.5, and 2.2. A Job wraps ``execution_manager.start()``;
it does not become a node. Job status derives from the execution record rather
than being tracked separately, so the two can never disagree (wired at 1.5).

The ordered stage list is *computed from the graph* here on the backend — a
hardcoded step array in the frontend would silently diverge the first time a
branch is added.
"""

from scriptase.jobs.channel_settings import (
    channel_settings_from_snapshot,
    merge_node_config_with_channel,
    merge_setup_config_with_channel,
    resolve_channel_settings,
    script_text_from_source,
    setup_seed_from_channel_settings,
)
from scriptase.jobs.execution_modes import (
    AUTOMATIC_MAX_REPAIRS_PER_SCENE,
    AUTOMATIC_PROVIDER_RETRIES,
    AUTOMATIC_SAFE_DEGRADATION_DEFAULTS,
    MANUAL_DEFAULT_CHECKPOINT_STAGES,
    ExecutionPolicy,
    apply_execution_policy_to_workflow,
    configured_checkpoint_refs,
    human_checkpoints_from_snapshot,
    normalize_execution_mode,
    resolve_checkpoint_node_ids,
    resolve_execution_policy,
    should_pause_for_escalation,
)
from scriptase.jobs.source_modes import (
    DIRECT_TEXT_SOURCE_MODES,
    EXECUTION_MODE_CATALOG,
    PROVIDER_REQUIRED_SOURCE_MODES,
    SOURCE_MODE_CATALOG,
    job_creation_catalog,
    source_mode_label,
    source_mode_requires_provider,
    validate_job_source,
)
from scriptase.jobs.models import (
    EXECUTION_MODES,
    JOB_ID_RE,
    JOB_SCHEMA_VERSION,
    JOB_STATUSES,
    SOURCE_MODES,
    STATUS_REASON_CODES,
    TERMINAL_STATUSES,
    BudgetSpent,
    Job,
    JobDraft,
    JobSource,
    parse_draft,
    parse_job,
    validation_problems,
)
from scriptase.jobs.migrations import SCHEMA_VERSION, apply_migrations
from scriptase.jobs.budget import (
    BudgetExceededError,
    budget_from_job,
    check_budget_preflight,
    check_job_next_stage_budget,
    estimate_stage_generations,
    next_provider_stage,
)
from scriptase.jobs.cost import (
    DEFAULT_FX_RATES,
    DEFAULT_REPORT_CURRENCY,
    CostRecord,
    accumulate_spend,
    apply_job_spend_from_execution,
    budget_spent_from_execution,
    build_channel_cost_report,
    build_cost_report,
    convert_amount,
    extract_cost_records_from_execution,
)
from scriptase.jobs.orchestration import (
    JobOrchestrationError,
    approve_job,
    assert_job_is_not_a_node,
    collect_execution_artifact_refs,
    derive_job_status,
    kind_for_artifact_ref,
    load_job_workflow,
    prepare_workflow_for_job,
    reject_job,
    run_job_repair_cycles,
    start_job,
    sync_job_from_execution,
    wait_for_job,
)
from scriptase.jobs.snapshot import (
    assert_snapshot_has_no_credentials,
    build_channel_snapshot,
    snapshot_contains_credentials,
)
from scriptase.jobs.triggers import (
    TRIGGER_SOURCES,
    TriggerEnqueueError,
    cadence_source_payload,
    create_and_start_triggered_job,
    create_job_from_channel_cadence,
    create_triggered_job,
    enqueue_scheduled_workflow,
    enqueue_watch_workflow,
    enqueue_webhook_workflow,
    resolve_trigger_channel_id,
    start_triggered_job,
)
from scriptase.jobs.store import (
    JobNotFound,
    JobTerminal,
    JobValidationError,
    add_artifact_ids,
    add_issue_ids,
    add_repair_history_ids,
    create_job,
    default_draft,
    delete_job,
    get_job,
    job_summary,
    list_jobs,
    update_job,
)
from scriptase.jobs.stage_actions import (
    ACTION_RUN_MODES,
    EXECUTABLE_STAGE_ACTIONS,
    STAGE_ACTIONS,
    StageActionError,
    action_requires_provider,
    build_stage_run_request,
    is_executable_action,
    normalize_execution_record_for_compare,
    run_mode_for_action,
    stage_for_key,
    stage_primary_target,
)
from scriptase.jobs.stage_projection import (
    STAGE_CATALOG,
    STAGE_KEYS,
    StageProjectionError,
    assign_nodes_to_stages,
    default_stage_labels,
    project_stages,
    project_workflow_stages,
    stage_projection_summary,
)


# Lazy blueprint export so importing this package never pulls Flask routes.
def __getattr__(name: str):
    if name == "jobs_bp":
        from scriptase.jobs.routes import jobs_bp

        return jobs_bp
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "EXECUTION_MODES",
    "JOB_ID_RE",
    "JOB_SCHEMA_VERSION",
    "JOB_STATUSES",
    "SCHEMA_VERSION",
    "SOURCE_MODES",
    "STATUS_REASON_CODES",
    "TERMINAL_STATUSES",
    "BudgetSpent",
    "Job",
    "JobDraft",
    "JobNotFound",
    "JobOrchestrationError",
    "JobSource",
    "JobTerminal",
    "JobValidationError",
    "ACTION_RUN_MODES",
    "EXECUTABLE_STAGE_ACTIONS",
    "STAGE_ACTIONS",
    "STAGE_CATALOG",
    "STAGE_KEYS",
    "StageActionError",
    "StageProjectionError",
    "action_requires_provider",
    "add_artifact_ids",
    "add_issue_ids",
    "add_repair_history_ids",
    "apply_migrations",
    "approve_job",
    "assert_job_is_not_a_node",
    "assert_snapshot_has_no_credentials",
    "assign_nodes_to_stages",
    "BudgetExceededError",
    "CostRecord",
    "DEFAULT_FX_RATES",
    "DEFAULT_REPORT_CURRENCY",
    "accumulate_spend",
    "apply_job_spend_from_execution",
    "budget_from_job",
    "budget_spent_from_execution",
    "build_channel_cost_report",
    "build_channel_snapshot",
    "build_cost_report",
    "build_stage_run_request",
    "convert_amount",
    "extract_cost_records_from_execution",
    "channel_settings_from_snapshot",
    "check_budget_preflight",
    "check_job_next_stage_budget",
    "collect_execution_artifact_refs",
    "AUTOMATIC_MAX_REPAIRS_PER_SCENE",
    "AUTOMATIC_PROVIDER_RETRIES",
    "AUTOMATIC_SAFE_DEGRADATION_DEFAULTS",
    "DIRECT_TEXT_SOURCE_MODES",
    "EXECUTION_MODE_CATALOG",
    "ExecutionPolicy",
    "MANUAL_DEFAULT_CHECKPOINT_STAGES",
    "apply_execution_policy_to_workflow",
    "configured_checkpoint_refs",
    "estimate_stage_generations",
    "human_checkpoints_from_snapshot",
    "PROVIDER_REQUIRED_SOURCE_MODES",
    "SOURCE_MODE_CATALOG",
    "create_job",
    "default_draft",
    "default_stage_labels",
    "delete_job",
    "derive_job_status",
    "get_job",
    "is_executable_action",
    "job_creation_catalog",
    "job_summary",
    "jobs_bp",
    "kind_for_artifact_ref",
    "list_jobs",
    "load_job_workflow",
    "merge_node_config_with_channel",
    "merge_setup_config_with_channel",
    "next_provider_stage",
    "normalize_execution_mode",
    "normalize_execution_record_for_compare",
    "parse_draft",
    "parse_job",
    "project_stages",
    "project_workflow_stages",
    "reject_job",
    "resolve_channel_settings",
    "resolve_checkpoint_node_ids",
    "resolve_execution_policy",
    "run_mode_for_action",
    "setup_seed_from_channel_settings",
    "should_pause_for_escalation",
    "prepare_workflow_for_job",
    "script_text_from_source",
    "snapshot_contains_credentials",
    "source_mode_label",
    "source_mode_requires_provider",
    "stage_for_key",
    "stage_primary_target",
    "stage_projection_summary",
    "run_job_repair_cycles",
    "start_job",
    "start_triggered_job",
    "sync_job_from_execution",
    "TRIGGER_SOURCES",
    "TriggerEnqueueError",
    "update_job",
    "validate_job_source",
    "validation_problems",
    "wait_for_job",
    "cadence_source_payload",
    "create_and_start_triggered_job",
    "create_job_from_channel_cadence",
    "create_triggered_job",
    "enqueue_scheduled_workflow",
    "enqueue_watch_workflow",
    "enqueue_webhook_workflow",
    "resolve_trigger_channel_id",
]
